trigger:
  branches:
    include:
    - main
  paths:
    include: 
    - 'assets/i18n'

pr: none

variables:
  storage: 'ambassadorcomponents'
  component: 'i18n'
  subscription: 'devops'
  environment: 'PROD'

stages:
- stage: Deploy
  displayName: Deploy
  jobs:  
  - job: Deploy
    displayName: Deploy to blob storage
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureFileCopy@2
      displayName: 'Copy localisation files to blob'
      inputs:
        sourcePath: '$(Build.Repository.LocalPath)/assets/i18n'
        additionalArgumentsForBlobCopy: | 
          '/Y'
          '/Pattern:*.json' 
        azureSubscription: $(subscription)
        destination: AzureBlob
        storage: $(storage)
        containerName: 'assets/$(component)'
    - task: AzureFileCopy@2
      displayName: 'Copy localisation files to blob for Latest'
      inputs:
        sourcePath: '$(Build.Repository.LocalPath)/assets/i18n'
        additionalArgumentsForBlobCopy: | 
          '/Y'
          '/Pattern:*.json' 
        azureSubscription: $(subscription)
        destination: AzureBlob
        storage: $(storage)
        containerName: 'assets/$(component)'